markdown: rdiscount
highlighter: pygments
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Matt Beedle
production_url : http://blog.mattbeedle.name
description: "Blog attempt 5, by Matt Beedle"
disqus_shortname: mattbeedleblog
analytics: UA-43466624-1
author :
  name : Matt Beedle
  github : mattbeedle
  twitter : mattbeedle
  email: mattbeedle@gmail.com
baseurl:
